# Generated by Django 4.1 on 2022-10-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_sam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sam',
        ),
    ]
